// Curated Player Pool for IPL Mega Auction
export const PLAYERS_DATABASE = [
  // --- SET 1: MARQUEE PLAYERS ---
  {
    id: 1,
    name: "Virat Kohli",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Batsman",
    set: "Set 1: Marquee",
    basePrice: 200, // ₹2.00 Cr
    rating: 98,
    avatar: "👑",
    stats: { matches: 252, runs: 8004, strikeRate: 131.9, average: 38.6, wickets: 4, economy: 8.8 },
    bio: "Highest run-scorer in IPL history, former captain, dynamic anchor and chase master."
  },
  {
    id: 2,
    name: "Rohit Sharma",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Batsman",
    set: "Set 1: Marquee",
    basePrice: 200,
    rating: 96,
    avatar: "🏏",
    stats: { matches: 257, runs: 6628, strikeRate: 131.1, average: 29.7, wickets: 15, economy: 8.0 },
    bio: "5-time IPL champion captain, ruthless powerplay opener and aggressive pull-shot maestro."
  },
  {
    id: 3,
    name: "Jasprit Bumrah",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Fast Bowler",
    set: "Set 1: Marquee",
    basePrice: 200,
    rating: 99,
    avatar: "🎯",
    stats: { matches: 133, runs: 67, strikeRate: 98.5, average: 9.5, wickets: 165, economy: 7.3 },
    bio: "World's premier death-overs yorker specialist with unmatched economy in T20 cricket."
  },
  {
    id: 4,
    name: "Rishabh Pant",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Wicket-Keeper",
    set: "Set 1: Marquee",
    basePrice: 200,
    rating: 95,
    avatar: "🧤",
    stats: { matches: 111, runs: 3284, strikeRate: 148.9, average: 35.3, wickets: 0, economy: 0 },
    bio: "Explosive southpaw wicket-keeper batsman with boundary-clearing audacity in crunch moments."
  },
  {
    id: 5,
    name: "Heinrich Klaasen",
    country: "South Africa",
    countryCode: "SA",
    isOverseas: true,
    role: "Wicket-Keeper",
    set: "Set 1: Marquee",
    basePrice: 200,
    rating: 97,
    avatar: "💥",
    stats: { matches: 35, runs: 993, strikeRate: 168.3, average: 38.2, wickets: 0, economy: 0 },
    bio: "Most feared spin-hitter in modern white-ball cricket with colossal six-hitting range."
  },
  {
    id: 6,
    name: "Travis Head",
    country: "Australia",
    countryCode: "AUS",
    isOverseas: true,
    role: "Batsman",
    set: "Set 1: Marquee",
    basePrice: 200,
    rating: 96,
    avatar: "⚡",
    stats: { matches: 25, runs: 772, strikeRate: 182.5, average: 36.7, wickets: 3, economy: 9.8 },
    bio: "Ultra-aggressive top-order marauder who dismantles powerplay bowling at an 180+ strike rate."
  },
  {
    id: 7,
    name: "Shreyas Iyer",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Batsman",
    set: "Set 1: Marquee",
    basePrice: 200,
    rating: 94,
    avatar: "🦁",
    stats: { matches: 115, runs: 3127, strikeRate: 127.5, average: 32.2, wickets: 0, economy: 0 },
    bio: "Title-winning captain with supreme middle-overs spin domination and calm tactical composure."
  },
  {
    id: 8,
    name: "Mitchell Starc",
    country: "Australia",
    countryCode: "AUS",
    isOverseas: true,
    role: "Fast Bowler",
    set: "Set 1: Marquee",
    basePrice: 200,
    rating: 93,
    avatar: "🚀",
    stats: { matches: 41, runs: 116, strikeRate: 104.5, average: 10.5, wickets: 51, economy: 8.2 },
    bio: "Lethal left-arm swing and toe-crusher bowler for knockout matches and high-stakes finals."
  },

  // --- SET 2: BATSMEN ---
  {
    id: 9,
    name: "Suryakumar Yadav",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Batsman",
    set: "Set 2: Batsmen",
    basePrice: 200,
    rating: 97,
    avatar: "🌟",
    stats: { matches: 150, runs: 3594, strikeRate: 145.3, average: 32.1, wickets: 0, economy: 0 },
    bio: "Mr. 360 with revolutionary lap sweeps, scoops, and unmatchable field manipulation."
  },
  {
    id: 10,
    name: "Shubman Gill",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Batsman",
    set: "Set 2: Batsmen",
    basePrice: 200,
    rating: 95,
    avatar: "💎",
    stats: { matches: 103, runs: 3216, strikeRate: 135.7, average: 37.8, wickets: 0, economy: 0 },
    bio: "Orange Cap champion, classical strokeplay opener with elite run accumulation consistency."
  },
  {
    id: 11,
    name: "Yashasvi Jaiswal",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Batsman",
    set: "Set 2: Batsmen",
    basePrice: 200,
    rating: 94,
    avatar: "🔥",
    stats: { matches: 52, runs: 1607, strikeRate: 150.6, average: 32.8, wickets: 0, economy: 0 },
    bio: "Fearless left-handed opener holding the record for the fastest 50 in IPL history (13 balls)."
  },
  {
    id: 12,
    name: "Rinku Singh",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Batsman",
    set: "Set 2: Batsmen",
    basePrice: 150,
    rating: 93,
    avatar: "🛡️",
    stats: { matches: 45, runs: 893, strikeRate: 143.3, average: 30.8, wickets: 0, economy: 0 },
    bio: "Legendary 5-sixes death-overs finisher with nerves of steel in high-pressure chases."
  },
  {
    id: 13,
    name: "Ruturaj Gaikwad",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Batsman",
    set: "Set 2: Batsmen",
    basePrice: 200,
    rating: 94,
    avatar: "🎯",
    stats: { matches: 66, runs: 2380, strikeRate: 136.9, average: 41.7, wickets: 0, economy: 0 },
    bio: "Technically exquisite opener and captain who paces innings with clinical mastery."
  },
  {
    id: 14,
    name: "David Warner",
    country: "Australia",
    countryCode: "AUS",
    isOverseas: true,
    role: "Batsman",
    set: "Set 2: Batsmen",
    basePrice: 200,
    rating: 91,
    avatar: "🇦🇺",
    stats: { matches: 184, runs: 6565, strikeRate: 139.8, average: 40.5, wickets: 0, economy: 0 },
    bio: "Three-time Orange Cap winner and the most prolific overseas batsman in IPL history."
  },
  {
    id: 15,
    name: "Sai Sudharsan",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Batsman",
    set: "Set 2: Batsmen",
    basePrice: 100,
    rating: 89,
    avatar: "✨",
    stats: { matches: 25, runs: 1034, strikeRate: 139.2, average: 47.0, wickets: 0, economy: 0 },
    bio: "Elegant, high-consistency top-order technician with brilliant game awareness."
  },

  // --- SET 3: ALL-ROUNDERS ---
  {
    id: 16,
    name: "Hardik Pandya",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "All-Rounder",
    set: "Set 3: All-Rounders",
    basePrice: 200,
    rating: 96,
    avatar: "⚡",
    stats: { matches: 137, runs: 2525, strikeRate: 145.9, average: 28.7, wickets: 64, economy: 8.9 },
    bio: "Elite pace-bowling all-rounder, match-winning power hitter and IPL winning leader."
  },
  {
    id: 17,
    name: "Andre Russell",
    country: "West Indies",
    countryCode: "WI",
    isOverseas: true,
    role: "All-Rounder",
    set: "Set 3: All-Rounders",
    basePrice: 200,
    rating: 97,
    avatar: "💪",
    stats: { matches: 127, runs: 2484, strikeRate: 174.9, average: 29.2, wickets: 115, economy: 9.2 },
    bio: "Colossal monster hitter boasting an astonishing 174+ strike rate plus golden-arm death bowling."
  },
  {
    id: 18,
    name: "Ravindra Jadeja",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "All-Rounder",
    set: "Set 3: All-Rounders",
    basePrice: 200,
    rating: 95,
    avatar: "⚔️",
    stats: { matches: 240, runs: 2959, strikeRate: 129.7, average: 27.4, wickets: 160, economy: 7.6 },
    bio: "Three-dimensional legend: unplayable left-arm darts, rocket fielding arm, and clutch batting."
  },
  {
    id: 19,
    name: "Axar Patel",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "All-Rounder",
    set: "Set 3: All-Rounders",
    basePrice: 200,
    rating: 93,
    avatar: "🛡️",
    stats: { matches: 150, runs: 1653, strikeRate: 130.9, average: 20.9, wickets: 123, economy: 7.2 },
    bio: "Economical spin suffocator and ice-cool lower middle-order boundary striker."
  },
  {
    id: 20,
    name: "Sunil Narine",
    country: "West Indies",
    countryCode: "WI",
    isOverseas: true,
    role: "All-Rounder",
    set: "Set 3: All-Rounders",
    basePrice: 200,
    rating: 97,
    avatar: "🌪️",
    stats: { matches: 177, runs: 1534, strikeRate: 165.8, average: 17.2, wickets: 180, economy: 6.7 },
    bio: "MVP phenomenon who opens both the bowling with mystery spin and batting with ruthless blitzes."
  },
  {
    id: 21,
    name: "Glenn Maxwell",
    country: "Australia",
    countryCode: "AUS",
    isOverseas: true,
    role: "All-Rounder",
    set: "Set 3: All-Rounders",
    basePrice: 200,
    rating: 91,
    avatar: "🚀",
    stats: { matches: 134, runs: 2771, strikeRate: 156.7, average: 24.7, wickets: 37, economy: 8.3 },
    bio: "The Big Show: reverse sweep expert, rapid boundary accumulator and handy off-spinner."
  },
  {
    id: 22,
    name: "Marcus Stoinis",
    country: "Australia",
    countryCode: "AUS",
    isOverseas: true,
    role: "All-Rounder",
    set: "Set 3: All-Rounders",
    basePrice: 150,
    rating: 90,
    avatar: "💥",
    stats: { matches: 96, runs: 1866, strikeRate: 142.0, average: 28.3, wickets: 43, economy: 9.4 },
    bio: "Muscular power-hitter capable of single-handedly chasing down massive targets in the death overs."
  },

  // --- SET 4: FAST BOWLERS ---
  {
    id: 23,
    name: "Pat Cummins",
    country: "Australia",
    countryCode: "AUS",
    isOverseas: true,
    role: "Fast Bowler",
    set: "Set 4: Fast Bowlers",
    basePrice: 200,
    rating: 95,
    avatar: "🏆",
    stats: { matches: 58, runs: 515, strikeRate: 147.1, average: 17.8, wickets: 63, economy: 8.8 },
    bio: "World Cup winning captain, hard-hitting tailender and tactical pace spearhead."
  },
  {
    id: 24,
    name: "Mohammed Shami",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Fast Bowler",
    set: "Set 4: Fast Bowlers",
    basePrice: 200,
    rating: 94,
    avatar: "⚡",
    stats: { matches: 110, runs: 79, strikeRate: 90.8, average: 8.8, wickets: 127, economy: 8.4 },
    bio: "The seam presentation benchmark with lethal powerplay strikes and reverse swing mastery."
  },
  {
    id: 25,
    name: "Trent Boult",
    country: "New Zealand",
    countryCode: "NZ",
    isOverseas: true,
    role: "Fast Bowler",
    set: "Set 4: Fast Bowlers",
    basePrice: 200,
    rating: 93,
    avatar: "🎯",
    stats: { matches: 104, runs: 28, strikeRate: 75.7, average: 5.6, wickets: 121, economy: 8.3 },
    bio: "Undisputed first-over wicket taker in T20 cricket with vicious in-swinging deliveries."
  },
  {
    id: 26,
    name: "Matheesha Pathirana",
    country: "Sri Lanka",
    countryCode: "SL",
    isOverseas: true,
    role: "Fast Bowler",
    set: "Set 4: Fast Bowlers",
    basePrice: 150,
    rating: 94,
    avatar: "☄️",
    stats: { matches: 20, runs: 0, strikeRate: 0, average: 0, wickets: 34, economy: 7.9 },
    bio: "Slinga successor with searing 150 km/h toe-crushing yorkers that are virtually unhittable."
  },
  {
    id: 27,
    name: "Arshdeep Singh",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Fast Bowler",
    set: "Set 4: Fast Bowlers",
    basePrice: 200,
    rating: 93,
    avatar: "🏹",
    stats: { matches: 65, runs: 37, strikeRate: 74.0, average: 6.2, wickets: 76, economy: 8.7 },
    bio: "India's T20 World Cup leading left-arm seamer with supreme knuckle-ball death execution."
  },
  {
    id: 28,
    name: "Kagiso Rabada",
    country: "South Africa",
    countryCode: "SA",
    isOverseas: true,
    role: "Fast Bowler",
    set: "Set 4: Fast Bowlers",
    basePrice: 200,
    rating: 92,
    avatar: "🚀",
    stats: { matches: 80, runs: 207, strikeRate: 104.0, average: 11.5, wickets: 117, economy: 8.4 },
    bio: "Purple Cap winner with genuine thunderbolt pace and hostile bouncer precision."
  },
  {
    id: 29,
    name: "Harshit Rana",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Fast Bowler",
    set: "Set 4: Fast Bowlers",
    basePrice: 100,
    rating: 89,
    avatar: "🔥",
    stats: { matches: 21, runs: 20, strikeRate: 111.1, average: 10.0, wickets: 25, economy: 8.9 },
    bio: "Aggressive young tearaway with steep bounce, sharp cutters, and infectious energy."
  },

  // --- SET 5: SPIN BOWLERS ---
  {
    id: 30,
    name: "Rashid Khan",
    country: "Afghanistan",
    countryCode: "AFG",
    isOverseas: true,
    role: "Spin Bowler",
    set: "Set 5: Spin Bowlers",
    basePrice: 200,
    rating: 98,
    avatar: "🧙‍♂️",
    stats: { matches: 121, runs: 544, strikeRate: 147.8, average: 14.7, wickets: 149, economy: 6.8 },
    bio: "The world's gold standard leg-spinner: rapid googly, sub-7 economy and batting fireworks."
  },
  {
    id: 31,
    name: "Yuzvendra Chahal",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Spin Bowler",
    set: "Set 5: Spin Bowlers",
    basePrice: 200,
    rating: 96,
    avatar: "♟️",
    stats: { matches: 160, runs: 37, strikeRate: 46.8, average: 4.6, wickets: 205, economy: 7.8 },
    bio: "All-time highest wicket-taker in IPL history (200+ wickets) with cunning flight deception."
  },
  {
    id: 32,
    name: "Kuldeep Yadav",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Spin Bowler",
    set: "Set 5: Spin Bowlers",
    basePrice: 200,
    rating: 95,
    avatar: "🔮",
    stats: { matches: 84, runs: 126, strikeRate: 85.1, average: 9.7, wickets: 87, economy: 8.0 },
    bio: "Wrist-spinning wizard with drift, sharp turn both ways and high-percentage middle-over wickets."
  },
  {
    id: 33,
    name: "Varun Chakravarthy",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Spin Bowler",
    set: "Set 5: Spin Bowlers",
    basePrice: 150,
    rating: 93,
    avatar: "🌀",
    stats: { matches: 71, runs: 28, strikeRate: 60.9, average: 4.7, wickets: 83, economy: 7.5 },
    bio: "Architect mystery spinner with multiple variations: carrom ball, slider, and top spinner."
  },
  {
    id: 34,
    name: "Ravi Bishnoi",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Spin Bowler",
    set: "Set 5: Spin Bowlers",
    basePrice: 150,
    rating: 91,
    avatar: "⚡",
    stats: { matches: 66, runs: 28, strikeRate: 63.6, average: 5.6, wickets: 63, economy: 7.8 },
    bio: "Skiddy leg-spinner whose fast incoming googly is a constant nightmare for right-handers."
  },

  // --- SET 6: WICKET-KEEPERS ---
  {
    id: 35,
    name: "Sanju Samson",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Wicket-Keeper",
    set: "Set 6: Wicket-Keepers",
    basePrice: 200,
    rating: 94,
    avatar: "👑",
    stats: { matches: 167, runs: 4419, strikeRate: 138.9, average: 30.7, wickets: 0, economy: 0 },
    bio: "Cleanest striker of a cricket ball, calm franchise leader and agile glovesman."
  },
  {
    id: 36,
    name: "Nicholas Pooran",
    country: "West Indies",
    countryCode: "WI",
    isOverseas: true,
    role: "Wicket-Keeper",
    set: "Set 6: Wicket-Keepers",
    basePrice: 200,
    rating: 95,
    avatar: "💥",
    stats: { matches: 76, runs: 1769, strikeRate: 162.3, average: 32.2, wickets: 0, economy: 0 },
    bio: "Sensational southpaw with one of the fastest hands and highest boundary percentages in the world."
  },
  {
    id: 37,
    name: "Ishan Kishan",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Wicket-Keeper",
    set: "Set 6: Wicket-Keepers",
    basePrice: 200,
    rating: 91,
    avatar: "⚡",
    stats: { matches: 105, runs: 2644, strikeRate: 135.9, average: 28.4, wickets: 0, economy: 0 },
    bio: "Pocket dynamite opener who attacks bowlers with intent and savage leg-side pull shots."
  },
  {
    id: 38,
    name: "Phil Salt",
    country: "England",
    countryCode: "ENG",
    isOverseas: true,
    role: "Wicket-Keeper",
    set: "Set 6: Wicket-Keepers",
    basePrice: 150,
    rating: 92,
    avatar: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    stats: { matches: 21, runs: 653, strikeRate: 175.5, average: 36.3, wickets: 0, economy: 0 },
    bio: "English powerhouse who redefined modern powerplay aggression with a breathtaking 175+ SR."
  },
  {
    id: 39,
    name: "Jitesh Sharma",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Wicket-Keeper",
    set: "Set 6: Wicket-Keepers",
    basePrice: 100,
    rating: 88,
    avatar: "🧤",
    stats: { matches: 40, runs: 730, strikeRate: 151.1, average: 22.8, wickets: 0, economy: 0 },
    bio: "High-impact lower order designated boundary hitter ready to attack from ball one."
  },
  {
    id: 40,
    name: "MS Dhoni",
    country: "India",
    countryCode: "IND",
    isOverseas: false,
    role: "Wicket-Keeper",
    set: "Set 6: Wicket-Keepers",
    basePrice: 200,
    rating: 96,
    avatar: "🦁",
    stats: { matches: 264, runs: 5243, strikeRate: 137.5, average: 39.1, wickets: 0, economy: 0 },
    bio: "5-time champion, iconic captain cool, legendary death finisher and 0.1s lightning stumping master."
  }
];
