// IPL Franchises Data & Initial Configurations (Mega Auction 2025/2026)
export const INITIAL_TEAMS = [
  {
    id: "csk",
    name: "Chennai Super Kings",
    shortName: "CSK",
    city: "Chennai",
    color: "#F9CD05",
    accentColor: "#005DAA",
    textColor: "#111111",
    badgeText: "CSK",
    purse: 10000, // In Lakhs (100.00 Cr)
    initialPurse: 10000,
    players: [],
    overseasCount: 0,
    minPlayers: 18,
    maxPlayers: 25,
    maxOverseas: 8,
    isUser: false,
    priorityRoles: ["All-Rounder", "Spin Bowler", "Batsman"]
  },
  {
    id: "mi",
    name: "Mumbai Indians",
    shortName: "MI",
    city: "Mumbai",
    color: "#004BA0",
    accentColor: "#D1AB3E",
    textColor: "#FFFFFF",
    badgeText: "MI",
    purse: 10000,
    initialPurse: 10000,
    players: [],
    overseasCount: 0,
    minPlayers: 18,
    maxPlayers: 25,
    maxOverseas: 8,
    isUser: false,
    priorityRoles: ["Fast Bowler", "Batsman", "All-Rounder"]
  },
  {
    id: "rcb",
    name: "Royal Challengers Bengaluru",
    shortName: "RCB",
    city: "Bengaluru",
    color: "#C8102E",
    accentColor: "#D1AB3E",
    textColor: "#FFFFFF",
    badgeText: "RCB",
    purse: 10000,
    initialPurse: 10000,
    players: [],
    overseasCount: 0,
    minPlayers: 18,
    maxPlayers: 25,
    maxOverseas: 8,
    isUser: false,
    priorityRoles: ["Batsman", "Fast Bowler", "Wicket-Keeper"]
  },
  {
    id: "kkr",
    name: "Kolkata Knight Riders",
    shortName: "KKR",
    city: "Kolkata",
    color: "#3A225D",
    accentColor: "#EDD260",
    textColor: "#FFFFFF",
    badgeText: "KKR",
    purse: 10000,
    initialPurse: 10000,
    players: [],
    overseasCount: 0,
    minPlayers: 18,
    maxPlayers: 25,
    maxOverseas: 8,
    isUser: false,
    priorityRoles: ["All-Rounder", "Spin Bowler", "Fast Bowler"]
  },
  {
    id: "rr",
    name: "Rajasthan Royals",
    shortName: "RR",
    city: "Jaipur",
    color: "#EA1A85",
    accentColor: "#254AA5",
    textColor: "#FFFFFF",
    badgeText: "RR",
    purse: 10000,
    initialPurse: 10000,
    players: [],
    overseasCount: 0,
    minPlayers: 18,
    maxPlayers: 25,
    maxOverseas: 8,
    isUser: false,
    priorityRoles: ["Spin Bowler", "Batsman", "Wicket-Keeper"]
  },
  {
    id: "srh",
    name: "Sunrisers Hyderabad",
    shortName: "SRH",
    city: "Hyderabad",
    color: "#F26522",
    accentColor: "#111111",
    textColor: "#FFFFFF",
    badgeText: "SRH",
    purse: 10000,
    initialPurse: 10000,
    players: [],
    overseasCount: 0,
    minPlayers: 18,
    maxPlayers: 25,
    maxOverseas: 8,
    isUser: false,
    priorityRoles: ["Batsman", "Fast Bowler", "All-Rounder"]
  },
  {
    id: "gt",
    name: "Gujarat Titans",
    shortName: "GT",
    city: "Ahmedabad",
    color: "#1B2133",
    accentColor: "#D9B365",
    textColor: "#FFFFFF",
    badgeText: "GT",
    purse: 10000,
    initialPurse: 10000,
    players: [],
    overseasCount: 0,
    minPlayers: 18,
    maxPlayers: 25,
    maxOverseas: 8,
    isUser: false,
    priorityRoles: ["Fast Bowler", "Spin Bowler", "All-Rounder"]
  },
  {
    id: "lsg",
    name: "Lucknow Super Giants",
    shortName: "LSG",
    city: "Lucknow",
    color: "#0057E7",
    accentColor: "#F47C20",
    textColor: "#FFFFFF",
    badgeText: "LSG",
    purse: 10000,
    initialPurse: 10000,
    players: [],
    overseasCount: 0,
    minPlayers: 18,
    maxPlayers: 25,
    maxOverseas: 8,
    isUser: false,
    priorityRoles: ["Batsman", "All-Rounder", "Fast Bowler"]
  },
  {
    id: "dc",
    name: "Delhi Capitals",
    shortName: "DC",
    city: "Delhi",
    color: "#004C97",
    accentColor: "#EF4123",
    textColor: "#FFFFFF",
    badgeText: "DC",
    purse: 10000,
    initialPurse: 10000,
    players: [],
    overseasCount: 0,
    minPlayers: 18,
    maxPlayers: 25,
    maxOverseas: 8,
    isUser: false,
    priorityRoles: ["Wicket-Keeper", "Fast Bowler", "Batsman"]
  },
  {
    id: "pbks",
    name: "Punjab Kings",
    shortName: "PBKS",
    city: "Mohali",
    color: "#DD1F2D",
    accentColor: "#B2B2B2",
    textColor: "#FFFFFF",
    badgeText: "PBKS",
    purse: 10000,
    initialPurse: 10000,
    players: [],
    overseasCount: 0,
    minPlayers: 18,
    maxPlayers: 25,
    maxOverseas: 8,
    isUser: false,
    priorityRoles: ["All-Rounder", "Fast Bowler", "Batsman"]
  }
];

export function formatPrice(lakhs) {
  if (lakhs === 0) return "₹0";
  if (lakhs >= 100) {
    const cr = lakhs / 100;
    return `₹${cr % 1 === 0 ? cr.toFixed(0) : cr.toFixed(2)} Cr`;
  }
  return `₹${lakhs} Lakh`;
}
